
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files (x86)/CMake/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
